### ISSUE TITLE
Unable to create Warehouse: QUERY_ACCELERATION_MAX_SCALE_FACTOR error

### ISSUE THREAD

**Issue by istvan-fodor** [pulumi/pulumi-snowflake#172]
### What happened?

I am trying to create a warehouse using Pulumi Snowflake but I get an error message when I try:

```
warehouse = snowflake.Warehouse("warehouse",
        name=f"MY_WAREHOUSE",
        auto_resume = True,
        initially_suspended=True,
        auto_suspend=120,
        warehouse_size='X-SMALL')
```

The error message is the following:
```
error: 1 error occurred:
    	* error creating warehouse err = 001423 (22023): SQL compilation error:
    invalid property 'QUERY_ACCELERATION_MAX_SCALE_FACTOR'; feature 'Query Acceleration Service' not enabled
```

### Steps to reproduce

Create a warehouse using Pulumi Snowflake on Snowflake Standard edition. 

### Expected Behavior

I expected the warehouse to be created. I also expected that Pulumi / TF would ignore the QUERY_ACCELERATION_MAX_SCALE_FACTOR parameter on Snowflake Standard edition.

### Actual Behavior

Warehouse is not created, instead got an error message. 

The error message is the following:
```
error: 1 error occurred:
    	* error creating warehouse err = 001423 (22023): SQL compilation error:
    invalid property 'QUERY_ACCELERATION_MAX_SCALE_FACTOR'; feature 'Query Acceleration Service' not enabled
```

### Output of `pulumi about`

```
CLI
Version      3.51.0
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME       VERSION
python     unknown
random     4.8.2
snowflake  0.15.0
tls        4.6.1

Host
OS       darwin
Version  13.0
Arch     arm64

This project is written in python: executable='/Users/istvanfodor/Documents/Projects/Github/antares-idl-fix/deployment/snowflake/venv/bin/python3' version='3.11.0
'

Current Stack: starschema/antares-idl-snowflake/dev

TYPE                                         URN
pulumi:pulumi:Stack                          urn:pulumi:dev::antares-idl-snowflake::pulumi:pulumi:Stack::antares-idl-snowflake-dev
pulumi:providers:snowflake                   urn:pulumi:dev::antares-idl-snowflake::pulumi:providers:snowflake::default_0_15_0
snowflake:index/database:Database            urn:pulumi:dev::antares-idl-snowflake::snowflake:index/database:Database::database-user
snowflake:index/role:Role                    urn:pulumi:dev::antares-idl-snowflake::snowflake:index/role:Role::antares-writer-role
snowflake:index/role:Role                    urn:pulumi:dev::antares-idl-snowflake::snowflake:index/role:Role::antares-reader-role
pulumi:providers:tls                         urn:pulumi:dev::antares-idl-snowflake::pulumi:providers:tls::default_4_6_1
pulumi:providers:random                      urn:pulumi:dev::antares-idl-snowflake::pulumi:providers:random::default_4_8_2
tls:index/privateKey:PrivateKey              urn:pulumi:dev::antares-idl-snowflake::tls:index/privateKey:PrivateKey::tls-key
snowflake:index/schema:Schema                urn:pulumi:dev::antares-idl-snowflake::snowflake:index/schema:Schema::database-schema
random:index/randomPassword:RandomPassword   urn:pulumi:dev::antares-idl-snowflake::random:index/randomPassword:RandomPassword::password
snowflake:index/databaseGrant:DatabaseGrant  urn:pulumi:dev::antares-idl-snowflake::snowflake:index/databaseGrant:DatabaseGrant::db-grant
snowflake:index/schemaGrant:SchemaGrant      urn:pulumi:dev::antares-idl-snowflake::snowflake:index/schemaGrant:SchemaGrant::writer-schema-grant-USAGE
snowflake:index/schemaGrant:SchemaGrant      urn:pulumi:dev::antares-idl-snowflake::snowflake:index/schemaGrant:SchemaGrant::reader-schema-grant-USAGE
snowflake:index/schemaGrant:SchemaGrant      urn:pulumi:dev::antares-idl-snowflake::snowflake:index/schemaGrant:SchemaGrant::writer-schema-grant-CREATE_TABLE
snowflake:index/schemaGrant:SchemaGrant      urn:pulumi:dev::antares-idl-snowflake::snowflake:index/schemaGrant:SchemaGrant::writer-schema-grant-CREATE_PIPE
snowflake:index/tableGrant:TableGrant        urn:pulumi:dev::antares-idl-snowflake::snowflake:index/tableGrant:TableGrant::reader-table-grant
snowflake:index/schemaGrant:SchemaGrant      urn:pulumi:dev::antares-idl-snowflake::snowflake:index/schemaGrant:SchemaGrant::writer-schema-grant-CREATE_STAGE


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/ifodor
User           ifodor
Organizations  ifodor, starschema

Dependencies:
NAME              VERSION
nob               0.8.2
pip               22.3.1
pulumi-random     4.8.2
pulumi-snowflake  0.15.0
pulumi-tls        4.6.1
setuptools        65.6.3
wheel             0.38.4

Pulumi locates its logs in /var/folders/0k/5cb46pm90dv17f7675zv7xlm0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by istvan-fodor** [comment]
This might be caused by this issue: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1343

**Comment by mattotodd** [comment]
Seeing this too after upgrading to 0.15 and making no changes to my Warehouse configuration.

```
error: 1 error occurred:
	* updating urn:pulumi:***************::wsai:SnowflakeResources$snowflake:index/warehouse:Warehouse::TRANSFORMING_WAREHOUSE: 1 error occurred:
	* error altering warehouse err = 001423 (22023): SQL compilation error:
invalid property 'QUERY_ACCELERATION_MAX_SCALE_FACTOR'; feature 'Query Acceleration Service' not enabled
```

**Comment by guineveresaenger** [comment]
Thank you for finding the upstream issue @istvan-fodor. 

We'll pull in the resolution once it ships upstream!

**Comment by AaronFriel** [comment]
Hey @istvan-fodor, our latest release contains a fix for this! Please try v0.16.0 out and let us know.
